-- ==============================================================================
-- Supabase PostgreSQL Schema for AI Cold Outreach Platform
--
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard/project/_/sql
-- 2. Paste this entire file into the SQL Editor.
-- 3. Click "Run" to initialize all tables, indexes, and security policies.
-- ==============================================================================

-- 1. Contacts Table
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    company TEXT NOT NULL,
    job_title TEXT,
    linkedin_url TEXT,
    email TEXT UNIQUE NOT NULL,
    notes TEXT,
    website TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING_RESEARCH',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_contacts_email ON public.contacts (email);
CREATE INDEX IF NOT EXISTS idx_contacts_status ON public.contacts (status);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON public.contacts (created_at DESC);

-- 2. Research Dossiers Table
CREATE TABLE IF NOT EXISTS public.research_dossiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL UNIQUE REFERENCES public.contacts(id) ON DELETE CASCADE,
    business_name TEXT,
    website_url TEXT,
    website_title TEXT,
    website_summary TEXT,
    detected_opportunities JSONB DEFAULT '[]'::jsonb,
    search_snippets JSONB DEFAULT '[]'::jsonb,
    user_pasted_content TEXT,
    verifiable_facts JSONB DEFAULT '[]'::jsonb,
    has_strong_hook BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_research_dossiers_contact_id ON public.research_dossiers (contact_id);

-- 3. Drafts Table
CREATE TABLE IF NOT EXISTS public.drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL UNIQUE REFERENCES public.contacts(id) ON DELETE CASCADE,
    hook TEXT NOT NULL,
    linkedin_note TEXT,
    linkedin_message TEXT,
    email_subject TEXT NOT NULL,
    email_subject_alt1 TEXT,
    email_subject_alt2 TEXT,
    email_body TEXT NOT NULL,
    followup_subject TEXT,
    followup_body TEXT,
    source_facts JSONB DEFAULT '[]'::jsonb,
    status TEXT NOT NULL DEFAULT 'PENDING',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_drafts_contact_id ON public.drafts (contact_id);
CREATE INDEX IF NOT EXISTS idx_drafts_status ON public.drafts (status);

-- 4. Send Logs Table
CREATE TABLE IF NOT EXISTS public.send_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
    draft_id BIGINT REFERENCES public.drafts(id) ON DELETE SET NULL,
    channel TEXT NOT NULL DEFAULT 'email',
    recipient TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    gmail_message_id TEXT,
    gmail_thread_id TEXT,
    is_dry_run BOOLEAN NOT NULL DEFAULT TRUE,
    status TEXT NOT NULL,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_send_logs_recipient ON public.send_logs (recipient);
CREATE INDEX IF NOT EXISTS idx_send_logs_sent_at ON public.send_logs (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_send_logs_status ON public.send_logs (status);

-- 5. Suppression List Table
CREATE TABLE IF NOT EXISTS public.suppression_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    reason TEXT,
    opted_out_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_suppression_list_email ON public.suppression_list (email);

-- 6. Daily Send Counter Table
CREATE TABLE IF NOT EXISTS public.daily_send_counter (
    send_date TEXT PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 0
);

-- 7. Automatic updated_at Trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_contacts_updated_at ON public.contacts;
CREATE TRIGGER set_contacts_updated_at
    BEFORE UPDATE ON public.contacts
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS set_drafts_updated_at ON public.drafts;
CREATE TRIGGER set_drafts_updated_at
    BEFORE UPDATE ON public.drafts
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- 8. Row Level Security (RLS) Policies
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_dossiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.send_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppression_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_send_counter ENABLE ROW LEVEL SECURITY;

-- Allow full access to service_role and anon authenticated clients
DO $$
BEGIN
    -- Contacts
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'contacts' AND policyname = 'Allow all access to contacts') THEN
        CREATE POLICY "Allow all access to contacts" ON public.contacts FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Dossiers
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'research_dossiers' AND policyname = 'Allow all access to research_dossiers') THEN
        CREATE POLICY "Allow all access to research_dossiers" ON public.research_dossiers FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Drafts
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'drafts' AND policyname = 'Allow all access to drafts') THEN
        CREATE POLICY "Allow all access to drafts" ON public.drafts FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Send Logs
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'send_logs' AND policyname = 'Allow all access to send_logs') THEN
        CREATE POLICY "Allow all access to send_logs" ON public.send_logs FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Suppression List
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'suppression_list' AND policyname = 'Allow all access to suppression_list') THEN
        CREATE POLICY "Allow all access to suppression_list" ON public.suppression_list FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Daily Send Counter
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_send_counter' AND policyname = 'Allow all access to daily_send_counter') THEN
        CREATE POLICY "Allow all access to daily_send_counter" ON public.daily_send_counter FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
