[theme]
base = "dark"
primaryColor = "#84cc16"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#121215"
textColor = "#f4f4f5"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false

